---
title: "Carlos Trucios" #espaço:\_\_\_\_\_ 
output:
  html_document:
    fig_width: 1
    
---



<style type="text/css">
.nav.navbar-nav.navbar-right a {
    color: white;
}
.navbar {
  background-color:maroon;
  border-color:black;
  icon-color:white;
}
.navbar-brand {
color:black!important;
}

body{ /* Normal  */
      font-size: 15px;
      background-color: white
  }
<!-- td {  /* Table  */ -->
<!--   font-size: 8px; -->
<!-- } -->
h1.title {
  font-size: 36px;
  <!-- color: DarkRed; -->
}
<!-- h1 { /* Header 1 */ -->
<!--   font-size: 28px; -->
<!--   color: DarkBlue; -->
<!-- } -->
<!-- h2 { /* Header 2 */ -->
<!--     font-size: 22px; -->
<!--   color: DarkBlue; -->
<!-- } -->
<!-- h3 { /* Header 3 */ -->
<!--   font-size: 18px; -->
<!--   font-family: "Times New Roman", Times, serif; -->
<!--   color: DarkBlue; -->
<!-- } -->
<!-- code.r{ /* Code block */ -->
<!--     font-size: 12px; -->
<!-- } -->
<!-- pre { /* Code block - determines code spacing between lines */ -->
<!--     font-size: 14px; -->
<!-- } -->
</style>

<style>
.column-left{
  float: left;
  width: 20%;
  text-align: center;
}
.column-right{
  float: right;
  width: 75%;
  text-align: left;
}
.column-center2{
  float: left;
  width: 33%;
  text-align: left;
}

.column-left2{
  float: left;
  width: 33%;
  text-align: left;
}

.column-right2{
  float: left;
  width: 33%;
  text-align: left;
}
.column{
  float: left;
  width: 100%;
  text-align: left;
} 
.column-f1{
  float: left;
  width: 20%;
  text-align: left;
}
.column-f2{
  float: right;
  width: 20%;
  text-align: right;
}
</style>
<link href="site_libs/academicons-1.8.6/css/academicons.min.css" rel="stylesheet" />
----

<div class="column-left">
![<a href= https://github.com/ctruciosm > <i class="fa fa-github-square fa-2x" aria-hidden="true" link =  ></i></a>
<a href= https://www.linkedin.com/in/ctrucios/ > <i class="fa fa-linkedin-square fa-2x" aria-hidden="true" link =  ></i></a>
<a href= http://lattes.cnpq.br/9315014843913122 > <i class="ai ai-lattes-square fa-2x" aria-hidden="true"></i> </a>
<a href= https://scholar.google.com/citations?user=HEdXeQkAAAAJ > <i class="ai ai-google-scholar-square fa-2x" aria-hidden="true"></i></a>
<a href= https://orcid.org/0000-0001-8746-8877 > <i class="ai ai-orcid-square fa-2x" aria-hidden="true"></i></a>
<a href= https://www.researchgate.net/profile/Carlos_Trucios > <i class="ai ai-researchgate-square fa-2x" aria-hidden="true"></i></a>](imagens/foto_ctrucios.jpeg)

**CONTACT** </br>
<i class="fa fa-envelope" aria-hidden="true"></i> 
ctrucios _at_ gmail  _dot_ com

</div>
<div class="column-right">

<span style="color:darkred"> **Data Scientist Consultant at Via Varejo** </span> </br>
<span style="color:darkred"> **Associate Researcher at Centre for Applied Research on Econometrics, Finance and Statistics (CAREFS)**</span></p>

I am a Ph.D. in statistics with a focus on applied statistics and financial econometrics, mainly, risk management, portfolio allocation, volatility forecasting, robust statistics, and statistical learning. I have been working on new procedures for modelling and forecasting volatility in financial time series as well as its applications to financial problems

I received the y-BIS Best Paper Award (ISBIS 2016 - Barcelona, Spain), IASC-ERS Young Researchers Award (COMPSTAT 2018 - Iasi, Romania), and also the best paper Award in the 4th Latin American Conference for Statistical Computing (LACSC 2019 - Guayaquil, Ecuador).  

Currently, my goal is to apply statistical learning techniques to financial problems as well as develop new volatility forecasting procedures in high-dimensional and high-frequency data.
</span>
</br>

<span style="color:darkred"> __Forthcomig events: __ </span> </br> 
</i> Bernoulli-IMS One World Symposium, August 2020 </br>
</i> International Symposium on Forecasting, October 2020 </br>
</i> X Encuentro Nacional de Matemáticas y Estadística, 2021 </br>


</div>

<div class="column">
----

<div class="column-left2">
<span style="color:darkred"> **Education** </span>

<i class="fa fa-graduation-cap" aria-hidden="true"></i> PhD in Statistics </br> <small> University of Campinas, 2016. Brazil </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Visiting PhD Student </br> <small> University Carlos III de Madrid, 2014. Spain </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i>   MSc in Statistics </br> <small> University of Campinas, 2012. Brazil </small>  </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i>   BSc in Statistics </br> <small> National University of San Marcos, 2009. Peru </small> 
</div>


<div class="column-center2">
<span style="color:darkred"> **Postdoctorate** </span>

<i class="fa fa-graduation-cap" aria-hidden="true"></i> Postdoctoral Researcher </br> <small> São Paulo School of Economics-FGV, </br> 2016-2019. Brazil </small> </br>
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Visiting Postdoctoral Researcher </br> <small> Université libre de Bruxelles, </br> 2018. Belgium </small> </br>
</div>

<div class="column-right2">
<span style="color:darkred"> **Interests** </span> </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Bootstrap procedures for dependent data </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> High dimensional data </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Risk measures and portfolio allocation </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Robust procedures and outliers </br> 
<i class="fa fa-graduation-cap" aria-hidden="true"></i> Statistical learning for financial econometrics </br> 
</div>





