---
title: "Introdução à Probabilidade e Estatística"
output:
  html_document:
    fig_width: 1
    toc_float: false    
---

<style type="text/css">
.nav.navbar-nav.navbar-right a {
    color: white;
}
.navbar {
  background-color:maroon;
  border-color:black;
  icon-color:white;
}
.navbar-brand {
color:black!important;
}
body{ /* Normal  */
      font-size: 15px;
  }
h1.title {
  font-size: 32px;
}
h3 { /* Header 3 */
  font-size: 24px;
  color: DarkRed;
}
</style>

<style>
a:link {
    color: darkred;
}
a:visited {
    color: darkred;
}
a:hover {
    color: blue;
}
.column-f1{
  float: left;
  width: 20%;
  text-align: left;
}
.column-f2{
  float: right;
  width: 20%;
  text-align: right;
}
</style>

----


**Lista 2 já está disponível**
[Lista 2](IPE/Lista2.pdf) 


**As notas da P1 e da Lista 1 (corrigida) já estão disponíveis**

[Gabarito da P1](IPE/P1.pdf) - 
[Notas P1 e L1](IPE/IPE_QS_2020_L1P1.xls)


**Lista 1**

[Lista 1](IPE/Lista1.pdf) - 
[Gabarito](IPE/Gabarito_Lista1.pdf) - 
[Notas](IPE/IPE_QS_2020_NOTAS_L1.xls) 


**Links importantes**

[Plano de Ensino](IPE/PlanoEnsino.pdf) 

[YouTube Channel](https://www.youtube.com/channel/UCrvm4mM1eoOn5WWCs08_-zg) 

[Conferenciaweb RNP](https://conferenciaweb.rnp.br/webconf/carlos-193)  (As aulas serão transmitidas por esse link nos dias e horários correspondentes a cada turma)

**Google Classroom**

- [Turma: NA8BIN0406-15SA](https://classroom.google.com/c/MTYxOTg3MTc4NTQ3?cjc=rgcl32o)
- [Turma: NB8BIN0406-15SA](https://classroom.google.com/c/MTYxOTg3MTc4Njg0?cjc=d45bfga)


**Horários**

- **NA8BIN0406-15SA:** segunda das 21:00 às 23:00 (semanal); quarta das 19:00 às 21:00 (quinzenal II).
- **NB8BIN0406-15SA:** segunda das 19:00 às 21:00 (semanal); quarta das 21:00 às 23:00 (quinzenal II). 



**Monitorias**

Horários de atendimento:

- Gabriel - Segunda-Feira das 17h às 19h;
- Gabriel - Terça-Feira das 17h às 19h;
- Mateus - Quarta-Feira das 14h às 16h;
- Mateus - Sexta-Feira das 16h às 18h.

Os atendimentos serão por email, facebook, moodle e alguma ferramenta remota.

O email do Gabriel é: g.tavares@aluno.ufabc.edu.br e link do conf web: https://conferenciaweb.rnp.br/webconf/gabriel-78

Do Mateus em princípio será: mateusborgiani@gmail.com ainda não temos o link para atendimento remoto


----


### **Aulas**



| Semana | Assunto                     | Data       | Video | Slides | Extras |
|--------|-----------------------------|------------|-------|--------|--------|
| 1      | Análise Combinatória  1     | 2020-09-21 | [Link](https://youtu.be/ULVoVQF9LQQ)  | [Link](IPE/Semana01_Aula01.pdf)  | [Link](https://www.math.tecnico.ulisboa.pt/~dpaulino/Combinatoria.pdf)   |
| 2      | Análise Combinatória  2     | 2020-09-28 | [Link](https://youtu.be/T8JZjRZE9go)  | [Link](IPE/Semana02_Aula01.pdf)  | [Link](https://youtu.be/7QKiLZGr_Io)  |
| 2      | Probabilidade 1     | 2020-09-30 | [Link](https://youtu.be/u4JqFOlH8oo)  | [Link](IPE/Semana02_Aula02.pdf)  | -  |
| 3      | Probabilidade 2     | 2020-10-05 | [Link](https://youtu.be/tHswU2eiYYU)  | [Link](IPE/Semana03.pdf)  | -  |
| 4      | Probabilidade Conditional 1     | 2020-10-12 | [Link](https://youtu.be/WF7baXvOWEQ)  | [Link](IPE/Semana04_Aula01.pdf)  | -  |
| 4      | Probabilidade Conditional 2     | 2020-10-14 |   | [Link](IPE/Semana04_Aula02.pdf)  | -  |
| 5      | Revisão     | 2020-10-19 |   | - | -  |
| 6      | Prova     | 2020-10-26 |   | - | -  |
| 6      | Variáveis aleatórias 1    | 2020-10-28 | [Link](https://youtu.be/wDQ4JPF1syo)  | [Link](IPE/Semana06.pdf)  | [Link](https://www.probabilitycourse.com/chapter3/3_1_1_random_variables.php)  |
| 7      | Variáveis aleatórias 2    | 2020-11-02 | [Link](https://youtu.be/PTmKMJxy164)  | [Link](IPE/Semana07.pdf) | [Binomial](http://www-eio.upc.es/teaching/pe/www.computing.dcu.ie/~jhorgan/chapter11slides.pdf) - [Poisson](http://www-eio.upc.es/teaching/pe/www.computing.dcu.ie/~jhorgan/chapter13slides.pdf)  |
| 8      | Variáveis aleatórias 3    | 2020-11-09 | [Link](https://youtu.be/Mia1tO5DNF8)  | [Link](IPE/Semana08_Aula1.pdf) |   |
| 8      | Variáveis aleatórias 4    | 2020-11-11 | [Link](https://youtu.be/KuTj-iileao)  | [Link](IPE/Semana08_Aula2.pdf) |   |











---- 
