---
title: "Modelos de Regressão e Previsão"
output:
  html_document:
    fig_width: 1
    toc_float: false    
---

<style type="text/css">
.nav.navbar-nav.navbar-right a {
    color: white;
}
.navbar {
  background-color:maroon;
  border-color:black;
  icon-color:white;
}
.navbar-brand {
color:black!important;
}
body{ /* Normal  */
      font-size: 15px;
  }
h1.title {
  font-size: 32px;
}
h3 { /* Header 3 */
  font-size: 24px;
  color: DarkRed;
}
</style>

<style>
a:link {
    color: darkred;
}
a:visited {
    color: darkred;
}
a:hover {
    color: blue;
}
.column-f1{
  float: left;
  width: 20%;
  text-align: left;
}
.column-f2{
  float: right;
  width: 20%;
  text-align: right;
}
</style>

----

**Lista 1 Liberada!**

[Lista 1](MRP/Lista1.pdf) 


**Links importantes**

[Plano de Ensino](MRP/PlanoEnsino.pdf) 

[YouTube Channel](https://www.youtube.com/playlist?list=PLrqJCLOY0EkDnnNuVz4FEKXoM6nDqxrgu) 

[Google Classroom](https://classroom.google.com/c/MjUwMTAwMjUyOTcy?cjc=pad4hj5)  (Código da Turma caso precisarem: gde3vhhxvi)

[Link Google Meet](https://meet.google.com/urk-dtqw-trp)  


**Horários**

Terças e Quintas das 16:40 às 18:20 (Turma B)
Terças e Quintas das 18:30 às 20:10 (Turma D)


**Monitorias**

Horários de atendimento:



----

### **Material e Aulas**

- Os conjuntos de dados que serão utilizados durante o curso estão disponíveis [aqui](MRP/DadosMRP.zip) 
- Baixe o apêndice do livro texto [aqui](MRP/Apendice_Livro.pdf) 


| Aula   | Assunto                           | Data       | Video | Slides | Extras |
|--------|-----------------------------------|------------|-------|--------|--------|
| 1      | Intro e Reg. Linear Simples       | 07/01/2021 | [Link](https://youtu.be/Hnb2mJs6nb8)  - [Link R](https://youtu.be/N360-J0MWwk)    | [link](MRP/Aula01.pdf)        | [Script R](MRP/EDA_Aula1.R)         |
| 2      | RLS: Estimação                    | 12/01/2021 |  [Link](https://youtu.be/GCK-38OrXWc)      |   [link](MRP/Aula02.pdf)      |   [Script R](MRP/RLS_Aula2.R)       |
| 3      | RLS: Interpretação e Propriedades | 14/01/2021 |       |   [link](MRP/Aula03.pdf)      |  [Script R](MRP/RLS_Aula3.R)  |
| 4      | Modelo de Regressão Linear Multipla (MRLM) | 19/01/2021 |       |   [link](MRP/Aula04.pdf)      | [Script R](MRP/MRLM_Aula4.R)        |
| 5      | MRLM: Inferência | 21/01/2021 |       |        |        |













---- 
